services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-app-instance
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/src  #  Assure que Python trouve vos dossiers de code
    volumes:
      - ./data/vdb_paris:/app/data/vdb_paris